- project:
    name: openstack/ansible-role-k8s-glance
    check:
      jobs:
        - ansible-role-k8s-glance-kubernetes-centos
        - ansible-role-k8s-glance-openshift-centos

- job:
    name: ansible-role-k8s-glance-kubernetes-centos
    parent:  ansible-role-k8s-base
    nodeset: ansible-role-k8s-centos
    vars:
      coe: kubernetes
      project_name: ansible-role-k8s-glance
      ansible_role_k8s_required:
        - ansible-role-k8s-mariadb
        - ansible-role-k8s-keystone
    required-projects:
      - openstack/ansible-role-k8s-mariadb
      - openstack/ansible-role-k8s-keystone
      - openstack/ansible-role-k8s-glance

- job:
    name: ansible-role-k8s-glance-openshift-centos
    parent:  ansible-role-k8s-base
    nodeset: ansible-role-k8s-centos
    vars:
      coe: openshift
      project_name: ansible-role-k8s-glance
      ansible_role_k8s_required:
        - ansible-role-k8s-mariadb
        - ansible-role-k8s-keystone
    required-projects:
      - openstack/ansible-role-k8s-mariadb
      - openstack/ansible-role-k8s-keystone
      - openstack/ansible-role-k8s-glance
