- name: Register Glance in Keystone
  include_role:
    name: ansible-role-k8s-tripleo
    tasks_from: bootstrap-service-endpoints
  vars:
    namespace: '{{namespace}}'
    clouds_config: '{{clouds_config}}'
    service_name: 'glance'
    service_type: 'image'
    service_region: 'RegionOne'
    service_project: '{{glance_config.keystone_authtoken.project}}'
    service_password: '{{glance_config.keystone_authtoken.password}}'
    service_username: '{{glance_config.keystone_authtoken.username}}'
    service_internal_url: '{{glance_config.keystone_internal_url}}'
    service_public_url: '{{glance_config.keystone_public_url}}'
    service_admin_url: '{{glance_config.keystone_admin_url}}'
