- name: Register Glance in Keystone
  include_role:
    name: ansible-role-k8s-tripleo
    tasks_from: bootstrap-service-endpoints
  vars:
#    service_name: '{{service_name}}'
    service_type: 'image'
    service_region: '{{glance_config.keystone_region}}'
    service_domain: '{{glance_config.keystone_default_domain}}'
    service_project: '{{glance_config.keystone_authtoken.project}}'
    service_password: '{{glance_config.keystone_authtoken.password}}'
    service_username: '{{glance_config.keystone_authtoken.username}}'
    service_internal_url: '{{ "https" if tls_enabled else "http"}}://{{glance_address}}:{{glance_port}}'
    service_public_url: '{{ "https" if tls_enabled else "http"}}://{{glance_address}}:{{glance_port}}'
    service_admin_url: '{{ "https" if tls_enabled else "http"}}://{{glance_address}}:{{glance_port}}'
